# Generated by Django 3.2.7 on 2021-09-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Keep the name short, if you can make it just one word.', max_length=50, unique=True)),
                ('icon', models.ImageField(help_text='Upload the category icon', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('start_date', models.DateTimeField(verbose_name='Date')),
                ('end_date', models.DateTimeField(verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20, verbose_name='Amount')),
                ('category', models.ManyToManyField(related_name='categories', to='expense.ExpenseCategory')),
            ],
        ),
    ]
