# Generated by Django 3.2.7 on 2021-09-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='end_date',
            field=models.DateTimeField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='start_date',
            field=models.DateTimeField(verbose_name='Start Date'),
        ),
    ]
